# Generated by Django 4.1.2 on 2022-10-13 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('manager', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'title')},
        ),
    ]
